version: '3.1'

volumes:
  grafana_data: {}

services:
  influxdb:
    image: tutum/influxdb:0.9
    restart: always
    environment:
      - PRE_CREATE_DB=cadvisor 
    ports:
     - "8083:8083"
     - "8086:8086"
    volumes:
      - ./data/influxdb:/data 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    privileged: true
    links:
      - influxdb:influxsrv
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: always
    ports:
     - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro 
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: always
    links:
      - influxdb:influxsrv
      - prometheus:prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana 